// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lb_database_open
SEXP lb_database_open(std::string path, bool read_only);
RcppExport SEXP _rladybugdb_lb_database_open(SEXP pathSEXP, SEXP read_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type read_only(read_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(lb_database_open(path, read_only));
    return rcpp_result_gen;
END_RCPP
}
// lb_database_close
void lb_database_close(SEXP db_xptr);
RcppExport SEXP _rladybugdb_lb_database_close(SEXP db_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_xptr(db_xptrSEXP);
    lb_database_close(db_xptr);
    return R_NilValue;
END_RCPP
}
// lb_database_version
std::string lb_database_version();
RcppExport SEXP _rladybugdb_lb_database_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lb_database_version());
    return rcpp_result_gen;
END_RCPP
}
// lb_connection_create
SEXP lb_connection_create(SEXP db_xptr, int num_threads);
RcppExport SEXP _rladybugdb_lb_connection_create(SEXP db_xptrSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_xptr(db_xptrSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_connection_create(db_xptr, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// lb_connection_close
void lb_connection_close(SEXP conn_xptr);
RcppExport SEXP _rladybugdb_lb_connection_close(SEXP conn_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type conn_xptr(conn_xptrSEXP);
    lb_connection_close(conn_xptr);
    return R_NilValue;
END_RCPP
}
// lb_connection_execute
SEXP lb_connection_execute(SEXP conn_xptr, std::string query);
RcppExport SEXP _rladybugdb_lb_connection_execute(SEXP conn_xptrSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type conn_xptr(conn_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(lb_connection_execute(conn_xptr, query));
    return rcpp_result_gen;
END_RCPP
}
// lb_connection_execute_params
SEXP lb_connection_execute_params(SEXP conn_xptr, std::string query, Rcpp::List params);
RcppExport SEXP _rladybugdb_lb_connection_execute_params(SEXP conn_xptrSEXP, SEXP querySEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type conn_xptr(conn_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_connection_execute_params(conn_xptr, query, params));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_num_tuples
int lb_result_num_tuples(SEXP res_xptr);
RcppExport SEXP _rladybugdb_lb_result_num_tuples(SEXP res_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type res_xptr(res_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_num_tuples(res_xptr));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_column_names
Rcpp::CharacterVector lb_result_column_names(SEXP res_xptr);
RcppExport SEXP _rladybugdb_lb_result_column_names(SEXP res_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type res_xptr(res_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_column_names(res_xptr));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_column_types
Rcpp::CharacterVector lb_result_column_types(SEXP res_xptr);
RcppExport SEXP _rladybugdb_lb_result_column_types(SEXP res_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type res_xptr(res_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_column_types(res_xptr));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_close
void lb_result_close(SEXP res_xptr);
RcppExport SEXP _rladybugdb_lb_result_close(SEXP res_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type res_xptr(res_xptrSEXP);
    lb_result_close(res_xptr);
    return R_NilValue;
END_RCPP
}
// lb_result_fetch_all
Rcpp::List lb_result_fetch_all(SEXP res_xptr);
RcppExport SEXP _rladybugdb_lb_result_fetch_all(SEXP res_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type res_xptr(res_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_fetch_all(res_xptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rladybugdb_lb_database_open", (DL_FUNC) &_rladybugdb_lb_database_open, 2},
    {"_rladybugdb_lb_database_close", (DL_FUNC) &_rladybugdb_lb_database_close, 1},
    {"_rladybugdb_lb_database_version", (DL_FUNC) &_rladybugdb_lb_database_version, 0},
    {"_rladybugdb_lb_connection_create", (DL_FUNC) &_rladybugdb_lb_connection_create, 2},
    {"_rladybugdb_lb_connection_close", (DL_FUNC) &_rladybugdb_lb_connection_close, 1},
    {"_rladybugdb_lb_connection_execute", (DL_FUNC) &_rladybugdb_lb_connection_execute, 2},
    {"_rladybugdb_lb_connection_execute_params", (DL_FUNC) &_rladybugdb_lb_connection_execute_params, 3},
    {"_rladybugdb_lb_result_num_tuples", (DL_FUNC) &_rladybugdb_lb_result_num_tuples, 1},
    {"_rladybugdb_lb_result_column_names", (DL_FUNC) &_rladybugdb_lb_result_column_names, 1},
    {"_rladybugdb_lb_result_column_types", (DL_FUNC) &_rladybugdb_lb_result_column_types, 1},
    {"_rladybugdb_lb_result_close", (DL_FUNC) &_rladybugdb_lb_result_close, 1},
    {"_rladybugdb_lb_result_fetch_all", (DL_FUNC) &_rladybugdb_lb_result_fetch_all, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rladybugdb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
