// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifdef __clang__
# pragma clang diagnostic push
# pragma clang diagnostic ignored "-Wunknown-warning-option"
#endif

#include <Rcpp.h>

#ifdef __clang__
# pragma clang diagnostic pop
#endif

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lb_database_open
SEXP lb_database_open(std::string path, Rcpp::List config);
RcppExport SEXP _rladybugdb_lb_database_open(SEXP pathSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_database_open(path, config));
    return rcpp_result_gen;
END_RCPP
}
// lb_database_close
void lb_database_close(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_database_close(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    lb_database_close(pointer);
    return R_NilValue;
END_RCPP
}
// lb_database_is_open
bool lb_database_is_open(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_database_is_open(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_database_is_open(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_database_version
std::string lb_database_version();
RcppExport SEXP _rladybugdb_lb_database_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lb_database_version());
    return rcpp_result_gen;
END_RCPP
}
// lb_database_storage_version
double lb_database_storage_version();
RcppExport SEXP _rladybugdb_lb_database_storage_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lb_database_storage_version());
    return rcpp_result_gen;
END_RCPP
}
// lb_connection_create
SEXP lb_connection_create(SEXP database_pointer, int num_threads);
RcppExport SEXP _rladybugdb_lb_connection_create(SEXP database_pointerSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type database_pointer(database_pointerSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_connection_create(database_pointer, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// lb_connection_close
void lb_connection_close(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_connection_close(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    lb_connection_close(pointer);
    return R_NilValue;
END_RCPP
}
// lb_connection_is_open
bool lb_connection_is_open(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_connection_is_open(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_connection_is_open(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_connection_interrupt_c
void lb_connection_interrupt_c(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_connection_interrupt_c(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    lb_connection_interrupt_c(pointer);
    return R_NilValue;
END_RCPP
}
// lb_connection_set_timeout_c
void lb_connection_set_timeout_c(SEXP pointer, double milliseconds);
RcppExport SEXP _rladybugdb_lb_connection_set_timeout_c(SEXP pointerSEXP, SEXP millisecondsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< double >::type milliseconds(millisecondsSEXP);
    lb_connection_set_timeout_c(pointer, milliseconds);
    return R_NilValue;
END_RCPP
}
// lb_connection_execute
SEXP lb_connection_execute(SEXP connection_pointer, std::string query);
RcppExport SEXP _rladybugdb_lb_connection_execute(SEXP connection_pointerSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connection_pointer(connection_pointerSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(lb_connection_execute(connection_pointer, query));
    return rcpp_result_gen;
END_RCPP
}
// lb_connection_execute_params
SEXP lb_connection_execute_params(SEXP connection_pointer, std::string query, Rcpp::List parameters);
RcppExport SEXP _rladybugdb_lb_connection_execute_params(SEXP connection_pointerSEXP, SEXP querySEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connection_pointer(connection_pointerSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_connection_execute_params(connection_pointer, query, parameters));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_num_tuples
double lb_result_num_tuples(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_num_tuples(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_num_tuples(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_column_names
Rcpp::CharacterVector lb_result_column_names(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_column_names(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_column_names(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_column_types
Rcpp::CharacterVector lb_result_column_types(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_column_types(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_column_types(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_is_open
bool lb_result_is_open(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_is_open(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_is_open(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_close
void lb_result_close(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_close(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    lb_result_close(pointer);
    return R_NilValue;
END_RCPP
}
// lb_result_has_next_c
bool lb_result_has_next_c(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_has_next_c(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_has_next_c(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_reset_c
void lb_result_reset_c(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_reset_c(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    lb_result_reset_c(pointer);
    return R_NilValue;
END_RCPP
}
// lb_result_fetch
Rcpp::List lb_result_fetch(SEXP pointer, double n, bool preserve_position, std::string bigint);
RcppExport SEXP _rladybugdb_lb_result_fetch(SEXP pointerSEXP, SEXP nSEXP, SEXP preserve_positionSEXP, SEXP bigintSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type preserve_position(preserve_positionSEXP);
    Rcpp::traits::input_parameter< std::string >::type bigint(bigintSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_fetch(pointer, n, preserve_position, bigint));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_info_c
Rcpp::List lb_result_info_c(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_info_c(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_info_c(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_summary_c
Rcpp::List lb_result_summary_c(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_summary_c(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_summary_c(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_result_next_result_c
SEXP lb_result_next_result_c(SEXP pointer);
RcppExport SEXP _rladybugdb_lb_result_next_result_c(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_next_result_c(pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_arrow_allocate_c
Rcpp::List lb_arrow_allocate_c();
RcppExport SEXP _rladybugdb_lb_arrow_allocate_c() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lb_arrow_allocate_c());
    return rcpp_result_gen;
END_RCPP
}
// lb_result_fetch_arrow_c
Rcpp::List lb_result_fetch_arrow_c(SEXP pointer, double n, bool preserve_position);
RcppExport SEXP _rladybugdb_lb_result_fetch_arrow_c(SEXP pointerSEXP, SEXP nSEXP, SEXP preserve_positionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type preserve_position(preserve_positionSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_result_fetch_arrow_c(pointer, n, preserve_position));
    return rcpp_result_gen;
END_RCPP
}
// lb_connection_create_arrow_table_c
SEXP lb_connection_create_arrow_table_c(SEXP connection_pointer, std::string table, SEXP array_pointer, SEXP schema_pointer);
RcppExport SEXP _rladybugdb_lb_connection_create_arrow_table_c(SEXP connection_pointerSEXP, SEXP tableSEXP, SEXP array_pointerSEXP, SEXP schema_pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connection_pointer(connection_pointerSEXP);
    Rcpp::traits::input_parameter< std::string >::type table(tableSEXP);
    Rcpp::traits::input_parameter< SEXP >::type array_pointer(array_pointerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type schema_pointer(schema_pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_connection_create_arrow_table_c(connection_pointer, table, array_pointer, schema_pointer));
    return rcpp_result_gen;
END_RCPP
}
// lb_connection_drop_arrow_table_c
SEXP lb_connection_drop_arrow_table_c(SEXP connection_pointer, std::string table);
RcppExport SEXP _rladybugdb_lb_connection_drop_arrow_table_c(SEXP connection_pointerSEXP, SEXP tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connection_pointer(connection_pointerSEXP);
    Rcpp::traits::input_parameter< std::string >::type table(tableSEXP);
    rcpp_result_gen = Rcpp::wrap(lb_connection_drop_arrow_table_c(connection_pointer, table));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rladybugdb_lb_database_open", (DL_FUNC) &_rladybugdb_lb_database_open, 2},
    {"_rladybugdb_lb_database_close", (DL_FUNC) &_rladybugdb_lb_database_close, 1},
    {"_rladybugdb_lb_database_is_open", (DL_FUNC) &_rladybugdb_lb_database_is_open, 1},
    {"_rladybugdb_lb_database_version", (DL_FUNC) &_rladybugdb_lb_database_version, 0},
    {"_rladybugdb_lb_database_storage_version", (DL_FUNC) &_rladybugdb_lb_database_storage_version, 0},
    {"_rladybugdb_lb_connection_create", (DL_FUNC) &_rladybugdb_lb_connection_create, 2},
    {"_rladybugdb_lb_connection_close", (DL_FUNC) &_rladybugdb_lb_connection_close, 1},
    {"_rladybugdb_lb_connection_is_open", (DL_FUNC) &_rladybugdb_lb_connection_is_open, 1},
    {"_rladybugdb_lb_connection_interrupt_c", (DL_FUNC) &_rladybugdb_lb_connection_interrupt_c, 1},
    {"_rladybugdb_lb_connection_set_timeout_c", (DL_FUNC) &_rladybugdb_lb_connection_set_timeout_c, 2},
    {"_rladybugdb_lb_connection_execute", (DL_FUNC) &_rladybugdb_lb_connection_execute, 2},
    {"_rladybugdb_lb_connection_execute_params", (DL_FUNC) &_rladybugdb_lb_connection_execute_params, 3},
    {"_rladybugdb_lb_result_num_tuples", (DL_FUNC) &_rladybugdb_lb_result_num_tuples, 1},
    {"_rladybugdb_lb_result_column_names", (DL_FUNC) &_rladybugdb_lb_result_column_names, 1},
    {"_rladybugdb_lb_result_column_types", (DL_FUNC) &_rladybugdb_lb_result_column_types, 1},
    {"_rladybugdb_lb_result_is_open", (DL_FUNC) &_rladybugdb_lb_result_is_open, 1},
    {"_rladybugdb_lb_result_close", (DL_FUNC) &_rladybugdb_lb_result_close, 1},
    {"_rladybugdb_lb_result_has_next_c", (DL_FUNC) &_rladybugdb_lb_result_has_next_c, 1},
    {"_rladybugdb_lb_result_reset_c", (DL_FUNC) &_rladybugdb_lb_result_reset_c, 1},
    {"_rladybugdb_lb_result_fetch", (DL_FUNC) &_rladybugdb_lb_result_fetch, 4},
    {"_rladybugdb_lb_result_info_c", (DL_FUNC) &_rladybugdb_lb_result_info_c, 1},
    {"_rladybugdb_lb_result_summary_c", (DL_FUNC) &_rladybugdb_lb_result_summary_c, 1},
    {"_rladybugdb_lb_result_next_result_c", (DL_FUNC) &_rladybugdb_lb_result_next_result_c, 1},
    {"_rladybugdb_lb_arrow_allocate_c", (DL_FUNC) &_rladybugdb_lb_arrow_allocate_c, 0},
    {"_rladybugdb_lb_result_fetch_arrow_c", (DL_FUNC) &_rladybugdb_lb_result_fetch_arrow_c, 3},
    {"_rladybugdb_lb_connection_create_arrow_table_c", (DL_FUNC) &_rladybugdb_lb_connection_create_arrow_table_c, 4},
    {"_rladybugdb_lb_connection_drop_arrow_table_c", (DL_FUNC) &_rladybugdb_lb_connection_drop_arrow_table_c, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rladybugdb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
