# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lb_database_open <- function(path, read_only) {
    .Call(`_rladybugdb_lb_database_open`, path, read_only)
}

lb_database_close <- function(db_xptr) {
    invisible(.Call(`_rladybugdb_lb_database_close`, db_xptr))
}

lb_database_version <- function() {
    .Call(`_rladybugdb_lb_database_version`)
}

lb_connection_create <- function(db_xptr, num_threads) {
    .Call(`_rladybugdb_lb_connection_create`, db_xptr, num_threads)
}

lb_connection_close <- function(conn_xptr) {
    invisible(.Call(`_rladybugdb_lb_connection_close`, conn_xptr))
}

lb_connection_execute <- function(conn_xptr, query) {
    .Call(`_rladybugdb_lb_connection_execute`, conn_xptr, query)
}

lb_connection_execute_params <- function(conn_xptr, query, params) {
    .Call(`_rladybugdb_lb_connection_execute_params`, conn_xptr, query, params)
}

lb_result_num_tuples <- function(res_xptr) {
    .Call(`_rladybugdb_lb_result_num_tuples`, res_xptr)
}

lb_result_column_names <- function(res_xptr) {
    .Call(`_rladybugdb_lb_result_column_names`, res_xptr)
}

lb_result_column_types <- function(res_xptr) {
    .Call(`_rladybugdb_lb_result_column_types`, res_xptr)
}

lb_result_close <- function(res_xptr) {
    invisible(.Call(`_rladybugdb_lb_result_close`, res_xptr))
}

lb_result_fetch_all <- function(res_xptr) {
    .Call(`_rladybugdb_lb_result_fetch_all`, res_xptr)
}

