# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lb_database_open <- function(path, config) {
    .Call(`_rladybugdb_lb_database_open`, path, config)
}

lb_database_close <- function(pointer) {
    invisible(.Call(`_rladybugdb_lb_database_close`, pointer))
}

lb_database_is_open <- function(pointer) {
    .Call(`_rladybugdb_lb_database_is_open`, pointer)
}

lb_database_version <- function() {
    .Call(`_rladybugdb_lb_database_version`)
}

lb_database_storage_version <- function() {
    .Call(`_rladybugdb_lb_database_storage_version`)
}

lb_connection_create <- function(database_pointer, num_threads) {
    .Call(`_rladybugdb_lb_connection_create`, database_pointer, num_threads)
}

lb_connection_close <- function(pointer) {
    invisible(.Call(`_rladybugdb_lb_connection_close`, pointer))
}

lb_connection_is_open <- function(pointer) {
    .Call(`_rladybugdb_lb_connection_is_open`, pointer)
}

lb_connection_interrupt_c <- function(pointer) {
    invisible(.Call(`_rladybugdb_lb_connection_interrupt_c`, pointer))
}

lb_connection_set_timeout_c <- function(pointer, milliseconds) {
    invisible(.Call(`_rladybugdb_lb_connection_set_timeout_c`, pointer, milliseconds))
}

lb_connection_execute <- function(connection_pointer, query) {
    .Call(`_rladybugdb_lb_connection_execute`, connection_pointer, query)
}

lb_connection_execute_params <- function(connection_pointer, query, parameters) {
    .Call(`_rladybugdb_lb_connection_execute_params`, connection_pointer, query, parameters)
}

lb_result_num_tuples <- function(pointer) {
    .Call(`_rladybugdb_lb_result_num_tuples`, pointer)
}

lb_result_column_names <- function(pointer) {
    .Call(`_rladybugdb_lb_result_column_names`, pointer)
}

lb_result_column_types <- function(pointer) {
    .Call(`_rladybugdb_lb_result_column_types`, pointer)
}

lb_result_is_open <- function(pointer) {
    .Call(`_rladybugdb_lb_result_is_open`, pointer)
}

lb_result_close <- function(pointer) {
    invisible(.Call(`_rladybugdb_lb_result_close`, pointer))
}

lb_result_has_next_c <- function(pointer) {
    .Call(`_rladybugdb_lb_result_has_next_c`, pointer)
}

lb_result_reset_c <- function(pointer) {
    invisible(.Call(`_rladybugdb_lb_result_reset_c`, pointer))
}

lb_result_fetch <- function(pointer, n, preserve_position, bigint) {
    .Call(`_rladybugdb_lb_result_fetch`, pointer, n, preserve_position, bigint)
}

lb_result_info_c <- function(pointer) {
    .Call(`_rladybugdb_lb_result_info_c`, pointer)
}

lb_result_summary_c <- function(pointer) {
    .Call(`_rladybugdb_lb_result_summary_c`, pointer)
}

lb_result_next_result_c <- function(pointer) {
    .Call(`_rladybugdb_lb_result_next_result_c`, pointer)
}

lb_arrow_allocate_c <- function() {
    .Call(`_rladybugdb_lb_arrow_allocate_c`)
}

lb_result_fetch_arrow_c <- function(pointer, n, preserve_position) {
    .Call(`_rladybugdb_lb_result_fetch_arrow_c`, pointer, n, preserve_position)
}

lb_connection_create_arrow_table_c <- function(connection_pointer, table, array_pointer, schema_pointer) {
    .Call(`_rladybugdb_lb_connection_create_arrow_table_c`, connection_pointer, table, array_pointer, schema_pointer)
}

lb_connection_drop_arrow_table_c <- function(connection_pointer, table) {
    .Call(`_rladybugdb_lb_connection_drop_arrow_table_c`, connection_pointer, table)
}

